school_roster_app/urls.py
from django.urls import path
from . import views

app_name = "school"
urlpatterns = [
    path("", views.index, name="home"),
    path("staff/", views.list_staff, name="list_staff"),
    path("staff/<int:employee_id>/", views.staff_detail, name="staff_detail"),
    path("students/", views.list_students, name="list_students"),
    path("students/<int:school_id>/", views.student_detail, name="student_detail"),
]

school_roster_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('school_roster_app.urls')),
]

school_roster_app/models.py
from django.db import models
import json
import os.path

# Create your models here.

class School:
    def __init__(self, name):
        self.name = name
        self.staff = Staff.load_all()
        self.students = Student.load_all()

    def find_student_by_id(self, school_id):
        for student in self.students:
            if student.school_id == school_id:
                return student
        
        return None

    def find_staff_by_id(self, employee_id):
        for staff in self.staff:
            if staff.employee_id == employee_id:
                return staff
        
        return None

class Person:

    def __init__(self, name, age, password, role):
        self.name = name
        self.age = age
        self.password = password
        self.role = role

    @classmethod
    def load_all(cls):
        my_path = os.path.abspath(os.path.dirname(__file__))
        file_path = os.path.join(my_path, cls.DATA_FILE)
        
        people = []
        
        f = open(file_path)

        data = json.load(f)
        for i in data:
            people.append(cls(**dict(i)))

        return people

class Staff(Person):
    DATA_FILE = "../data/staff.json"

    def __init__(self, name, age, password, role, employee_id):
        super().__init__(name, age, password, role)
        self.employee_id = employee_id

    def __repr__(self):
        return f"staff: {self.name}"

class Student(Person):
    DATA_FILE = "../data/students.json"

    def __init__(self, name, age, password, role, school_id):
        super().__init__(name, age, password, role)
        self.school_id = school_id

    def __str__(self):
        return f"{self.name.upper()}\n--------------\nage: {self.age}\nid: {self.school_id}"

school_roster_app/views.py
from django.shortcuts import render
from .models import School

# Create your views here.

my_school = School("Django School") # create a school instance


def index(request):
    my_data = {"school_name": my_school.name}
    return render(request, "pages/index.html", my_data)


def list_staff(request):
    staff_list = my_school.staff
    data = { 'staff_list': staff_list }
    return render(request, 'pages/staff.html', data)
    
def staff_detail(request, employee_id):
    employee = ""
    for member in my_school.staff:
        if member.employee_id == int(employee_id):
            employee = member
    data = {'employee': employee}
    return render(request, 'pages/detail.html', data)


def list_students(request):
    student_list = my_school.students
    data = { 'student_list': student_list }
    return render(request, 'pages/student.html', data)


def student_detail(request, school_id):
    student = ""
    for member in my_school.students:
        if member.school_id == int(school_id):
            student = member
    data = {'student': student}
    return render(request, 'pages/studentdetail.html', data)

school_roster_app/templates/pages/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Detail Page</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <h1> Details about staff member: {{ employee.name}} </h1>
    <h2> Role: {{ employee.role }} </h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <h2>Age: {{ employee.age }}</h2>
    <h2>Employee ID: {{ employee.employee_id }}</h2>
    <h2>Password: {{ employee.password }}</h2>
    <a href="{% url 'school:home' %}"><b>Return to school home</b></a>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

school_roster_app/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{school_name}}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <h2>{{school_name}} Directory</h2>
    <ul>
        <li><a href= "{% url 'school:list_staff' %}">All Staff</a></li>
        <li><a href= "{% url 'school:list_students' %}">All Student</a></li>
    </ul>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

school_roster_app/templates/pages/staff.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Page</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <h2>Staff Directory</h2>
    {% if staff_list %}
    <ul>
        {% for member in staff_list %}
        <li><a href="{% url 'school:staff_detail' member.employee_id %}"><b>{{ member.name }}</b></a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'school:home' %}"><b>Return to school home</b></a>
    {% else %}
    <p>No staff are listed.</p>
    {% endif %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

school_roster_app/templates/pages/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Page</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <h2>Student Directory</h2>
    {% if student_list %}
    <ul>
        {% for student in student_list %}
        <li><a href="{% url 'school:student_detail' student.school_id %}"><b>{{ student.name }}</b></a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'school:home' %}"><b>Return to school home</b></a>
    {% else %}
    <p>No students are listed.</p>
    {% endif %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

school_roster_app/templates/pages/studentdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Detail Page</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <h1> Details about student: {{ student.name}} </h1>
    <h2> Role: {{ student.role }} </h2>
    <h2>Age: {{ student.age }}</h2>
    <h2>Student ID: {{ student.school_id }}</h2>
    <h2>Password: {{ student.password }}</h2>
    <a href="{% url 'school:home' %}"><b>Return to school home</b></a>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>